name: Add contributors
on:
  push:
    branches:
      - main
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - uses: fregante/setup-git-user@v1
    - name: Add contributors to test1
      run: |

        git remote rm origin
        git remote add origin https://github.com/basebom/test2.git
        git fetch
        git checkout main
        git pull origin main --allow-unrelated-histories
    - uses: BobAnkh/add-contributors@master
      with:
        CONTRIBUTOR: '## Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'

