name: Add contributors
on:
  push:
    branches:
      - main
jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    #   with:
    #     repository: Ge-Wit-t-Oit-Noit-Nie/2025-software
    #     # submodules: true
    - uses: actions/checkout@v2
    #   with:
    #     repository: Ge-Wit-t-Oit-Noit-Nie/hardware
    - uses: BobAnkh/add-contributors@master
      with:
        CONTRIBUTOR: '## Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '\README.md'
        COMMIT_MESSAGE: 'docs(about): update contributors'
        AVATAR_SHAPE: 'round'

